apiVersion: apps/v1
kind: Deployment
metadata:
   name: auth
spec:
   selector: 
      matchLabels:
         app: auth
   template:
      metadata:
         labels:
            app: auth
      spec: 
         containers:
          - name: auth
            image: cedronc/auth
            ports:
             - containerPort: 3000