apiVersion: apps/v1
kind: Deployment
metadata:
   name: chat
spec:
   selector: 
      matchLabels:
         app: chat
   template:
      metadata:
         labels:
            app: chat
      spec: 
         containers:
          - name: chat
            image: cedronc/chat
            ports:
             - containerPort: 3000